default:
	@echo Downloading GTFS schedule files ...
	@echo
	@curl -o _data/gtfs.zip https://cdn01.at.govt.nz/data/gtfs.zip

	@echo
	@echo Extracting files from ZIP archive ...
	@unzip _data/gtfs.zip -d _data/gtfs

	@echo
	@echo Creating GTFS database ...
	@echo "(not yet available)"
	@echo

	@echo Done.
